spring:
  application:
    name: ms-cloud-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ms-cartaorelm

server:
  port: 8085

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaulZone: http://localhost:8761/eureka